# Generated by Django 4.1 on 2022-08-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.ukvisitorguide.cn%2Fwp-content%2Fuploads%2F2015%2F11%2FFood-placeholder.jpg&f=1&nofb=1', max_length=500),
        ),
    ]
